apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
images:
  - name: registry.gitlab/my/image
    newTag: latest
    digest: placeholder # {"$imagepolicy": "flux-system:test-iua:digest"}
