apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
images:
  - name: registry.gitlab/my/image
    newTag: latest
    digest: sha256:cebe162d4ddbcca1b008cf8b7a8e787f30285b536850cb123887f9b81ab622ab # {"$imagepolicy": "flux-system:test-iua:digest"}
