apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
images:
  - name: registry.gitlab/my/image
    newTag: latest
    digest: sha256:26b912583bd671f4b12789763482aa4a169bfb58b1b68c17cfe8d6d17b7c1423 # {"$imagepolicy": "flux-system:test-iua:digest"}
